<a href="https://colab.research.google.com/github/JayTheCoder77/numpy-tut/blob/main/numpy-tricks-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Session 15 campusx numpy advanced tricks


In [1]:
import numpy as np

In [2]:
# sort - returns sorted copy of an array

a = np.random.randint(1,100,15)
a


array([40, 16, 54, 49, 79, 13, 34, 83, 82, 55, 35, 22, 95, 98, 91])

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[10, 94, 99, 90],
       [24, 53, 39,  8],
       [94, 44, 78, 92],
       [79, 74, 82, 18],
       [ 5, 18, 69, 70],
       [77,  4, 91,  9]])

In [8]:
np.sort(a)
np.sort(b , axis = 0) # row wise default for col axis - 0

# for descending order sorting
np.sort(a)[::-1]

array([98, 95, 91, 83, 82, 79, 55, 54, 49, 40, 35, 34, 22, 16, 13])

In [9]:
# append = give axis to append a value
np.append(a,200)

array([ 40,  16,  54,  49,  79,  13,  34,  83,  82,  55,  35,  22,  95,
        98,  91, 200])

In [11]:
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[10., 94., 99., 90.,  1.],
       [24., 53., 39.,  8.,  1.],
       [94., 44., 78., 92.,  1.],
       [79., 74., 82., 18.,  1.],
       [ 5., 18., 69., 70.,  1.],
       [77.,  4., 91.,  9.,  1.]])

In [12]:
# concatenate

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [14]:
# unique

e = np.array([1,1,1,1,1,1,1,2,2,2,2,3,4,5,6,7,8])
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
# expand dims

np.expand_dims(a,axis=0) # col
a.shape
np.expand_dims(a,axis=1).shape # row

(15, 1)

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [22]:
# np.where

# find all indices with value greater than 50

a
np.where(a > 50)

(array([ 2,  4,  7,  8,  9, 12, 13, 14]),)

In [23]:
# replace all valuess greater than 50 with 0
np.where(a > 50, 0 , a)


array([40, 16,  0, 49,  0, 13, 34,  0,  0,  0, 35, 22,  0,  0,  0])

In [25]:
np.where(a % 2 == 0 , 0 , a)

array([ 0,  0,  0, 49, 79, 13,  0, 83,  0, 55, 35,  0, 95,  0, 91])

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [26]:
# ARGMAX
a

array([40, 16, 54, 49, 79, 13, 34, 83, 82, 55, 35, 22, 95, 98, 91])

In [27]:
np.argmax(a)

13

In [31]:
b
np.argmax(b,axis=0)

array([2, 0, 0, 2])

In [32]:
# argmin

np.argmin(a)

5

In [33]:
# cumsum
# cumulative sum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [34]:
a

array([40, 16, 54, 49, 79, 13, 34, 83, 82, 55, 35, 22, 95, 98, 91])

In [35]:
np.cumsum(a)

array([ 40,  56, 110, 159, 238, 251, 285, 368, 450, 505, 540, 562, 657,
       755, 846])

In [36]:
np.cumsum(b) # if axis not provided 2d converteed to 1d

array([  10,  104,  203,  293,  317,  370,  409,  417,  511,  555,  633,
        725,  804,  878,  960,  978,  983, 1001, 1070, 1140, 1217, 1221,
       1312, 1321])

In [37]:
np.cumsum(b,axis=0)

array([[ 10,  94,  99,  90],
       [ 34, 147, 138,  98],
       [128, 191, 216, 190],
       [207, 265, 298, 208],
       [212, 283, 367, 278],
       [289, 287, 458, 287]])

In [38]:
np.cumsum(b,axis=1)

array([[ 10, 104, 203, 293],
       [ 24,  77, 116, 124],
       [ 94, 138, 216, 308],
       [ 79, 153, 235, 253],
       [  5,  23,  92, 162],
       [ 77,  81, 172, 181]])

In [39]:
# cumprod

np.cumprod(a)

array([                  40,                  640,                34560,
                    1693440,            133781760,           1739162880,
                59131537920,        4907917647360,      402449247083520,
          22134708589593600,   774714800635776000, -1403018459722479616,
       -4159545157668702208, -1807055829922680832,  1578616140422008832])

In [41]:
# percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis

In [42]:
a

array([40, 16, 54, 49, 79, 13, 34, 83, 82, 55, 35, 22, 95, 98, 91])

In [43]:
np.percentile(a,100)

98.0

In [46]:
np.percentile(a,0)
np.percentile(a,50) # 50 -> same as median
np.median(a)

54.0

In [ ]:
# histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [47]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 2, 1, 2, 2, 2, 0, 1, 2, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))