In [1]:
import numpy as np

np.corrcoef
Return Pearson product-moment correlation coefficients.

In [3]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,2,3,4,2])
np.corrcoef(salary,experience)

array([[1.        , 0.04224095],
       [0.04224095, 1.        ]])

np.isin
With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [12]:
a =  np.random.randint(0, 100, 15)
a

array([34, 59,  8, 41, 65, 71, 16, 66, 53, 68, 71, 67, 90, 63, 50])

In [14]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)
a[np.isin(a,items)]

array([90, 50])

np.flip
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [15]:
a

array([34, 59,  8, 41, 65, 71, 16, 66, 53, 68, 71, 67, 90, 63, 50])

In [16]:
np.flip(a)

array([50, 63, 90, 67, 71, 68, 53, 66, 16, 71, 65, 41,  8, 59, 34])

In [17]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
np.flip(b,axis=0)

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [19]:
np.flip(b)

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

np.put
The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [20]:
a

array([34, 59,  8, 41, 65, 71, 16, 66, 53, 68, 71, 67, 90, 63, 50])

In [21]:
np.put(a,[0,1],[110,530]) # permanent changes to array

In [22]:
a

array([110, 530,   8,  41,  65,  71,  16,  66,  53,  68,  71,  67,  90,
        63,  50])

np.delete
The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [23]:
np.delete(a,0)

array([530,   8,  41,  65,  71,  16,  66,  53,  68,  71,  67,  90,  63,
        50])

In [24]:
np.delete(a,[0,2,4])

array([530,  41,  71,  16,  66,  53,  68,  71,  67,  90,  63,  50])

Set functions
np.union1d
np.intersect1d
np.setdiff1d
np.setxor1d
np.in1d

In [25]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
np.intersect1d(m,n)

array([3, 4, 5])

In [28]:
np.setdiff1d(n,m)

array([6, 7])

In [29]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [31]:
m[np.in1d(m,1)]
np.in1d(m,1)

array([1])

np.clip
numpy.clip() function is used to Clip (limit) the values in an array.

In [32]:
np.clip(a,a_min = 25,a_max = 75)

array([75, 75, 25, 41, 65, 71, 25, 66, 53, 68, 71, 67, 75, 63, 50])