In [3]:
import numpy as np

SLICING NUMPY ARRAYS

In [4]:
np1 = np.array([1,2,3,4,5,6,7,8,9])

# return 2 3 4 5
print(np1[1:5])

[2 3 4 5]


return from something till end of array

In [5]:
print(np1[3:])

[4 5 6 7 8 9]


return negative slices

In [6]:
print(np1[-3:-1])

[7 8]


steps


In [7]:
print(np1[1:5:2])

[2 4]


steps on entire array

In [8]:
print(np1[::2])

[1 3 5 7 9]


slice 2-d array

In [10]:
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

pull out single item

In [11]:
print(np2[1,2])

8


In [12]:
print(np2[0:1,1:3])

[[2 3]]


include both this time



In [13]:
print(np2[0:2,1:3])

[[2 3]
 [7 8]]
