In [1]:
import numpy as np

search

In [13]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10,3])

In [15]:
x = np.where(np1 == 3)

In [16]:
print(x)

(array([ 2, 10]),)


In [17]:
print(x[0])

[ 2 10]


In [18]:
print(np1[x[0]])

[3 3]


return even items

In [19]:
y = np.where(np1 % 2 == 0)

In [20]:
print(y)

(array([1, 3, 5, 7, 9]),)


these are the indexes not the elements themselves

return odd

In [21]:
z = np.where(np1 % 2 != 0)
print(z)

(array([ 0,  2,  4,  6,  8, 10]),)
