In [1]:
import numpy as np

filter numpy arrays with boolean index lists

In [2]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10])


In [3]:
x = [True,True,False,False,False,False,False,False,False,False]

In [4]:
print(np1)
print(np1[x])

[ 1  2  3  4  5  6  7  8  9 10]
[1 2]


In [6]:
filtered = []
for n in np1:
    if n % 2 == 0:
        filtered.append(True)
    else:
        filtered.append(False)

In [7]:
print(np1)
print(filtered)
new = np1[filtered]
print(new)

[ 1  2  3  4  5  6  7  8  9 10]
[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


built in shortcut for filtering

In [8]:
filtered = np1 % 2 == 0
print(np1)
print(filtered)
print(np1[filtered])

[ 1  2  3  4  5  6  7  8  9 10]
[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]
