In [2]:
import numpy as np

BASICS

In [9]:
a = np.array([1,2,3])
print(a)
type(a)
a.dtype

[1 2 3]


dtype('int64')

In [13]:
b = np.array(["a","b","d","c"])
print(b)
type(b)
b.dtype
print(b.ndim)

['a' 'b' 'd' 'c']
1


In [11]:
c = np.array((2,3,5),dtype='f')
print(c)
type(c)
c.dtype

[2. 3. 5.]


dtype('float32')

In [16]:
a = np.array([[1,2,3] , [4,5,6]])
print(a.ndim)
a[0,2]

2


np.int64(3)

In [17]:
a = np.array([1,2,4,5,6,7,8,9,0])
print(a.shape)

(9,)


In [18]:
#range
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
#step
c = np.arange(0,10,2)
print(c)

[0 2 4 6 8]


In [21]:
#ZEROES
np4 = np.zeros(10)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
#mulitdimensional zeros
np5 = np.zeros((2,10))
print(np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [24]:
#full
np5 = np.full((10),6)
print(np5)

[6 6 6 6 6 6 6 6 6 6]


In [25]:
#mulitdimensional full
np5 = np.full((2,10),6)
print(np5)

[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]


In [27]:
# convert python lists to numpy
my_list = [1,2,3,4,5,6,7]
np8 = np.array(my_list)
print(np8[0])

1
