What is numpy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

Numpy Arrays Vs Python Sequences
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [1]:
import numpy as np

creating numpy arrays

In [3]:
a = np.array([1,2,3]) # 1d array also called vector
print(a)

[1 2 3]


In [4]:
b = np.array([[1,2,3] , [4,5,6]]). # 2d array also called matrix
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
# 3d array also called a tensor
c = np.array([[[1,2] , [3,4] , [5,6]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]]]


In [7]:
# dtype

np.array([1,2,3] , dtype = float)

array([1., 2., 3.])

In [9]:
np.array([0,2,3] , dtype = bool)

array([False,  True,  True])

In [10]:
np.array([0,2,3] , dtype = complex)

array([0.+0.j, 2.+0.j, 3.+0.j])

In [13]:
# arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [20]:
# reshape
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# np.ones and np.zeros
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
# np.random

np.random.random((3,3))

array([[0.08014762, 0.82041766, 0.00941203],
       [0.51269512, 0.77947036, 0.43005504],
       [0.21972125, 0.18923106, 0.54432126]])

In [28]:
# np.linspace() -> linearly spaced
# np.linspace(lower range , upper range , no of items)

np.linspace(-10,10,10)
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [32]:
# np.identity - create identity matrix

np.identity(3)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])