In [1]:
import numpy as np

In [3]:
a1 = np.array([1,2,3])

Changing Datatype

In [4]:
a1.dtype

dtype('int64')

In [6]:
a1.astype(np.int32)

array([1, 2, 3], dtype=int32)

In [7]:
a1.dtype

dtype('int64')

Array Operations

In [8]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [9]:
#scalar operation

# arithmetic

a1 = a1 ** 2

In [10]:
print(a1)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [13]:
# relational

a2 > 5
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [16]:
# vector operations

# arithmetic

a1 + a2

array([[ 12,  14,  18,  24],
       [ 32,  42,  54,  68],
       [ 84, 102, 122, 144]])

In [17]:
a1 - 2 * a2

array([[-24, -25, -24, -21],
       [-16,  -9,   0,  11],
       [ 24,  39,  56,  75]])

Array Functions

In [18]:
a1 = np.random.random((3,3))
a1 = np.round(a1 * 100)
a1

array([[15., 16., 94.],
       [ 1., 67., 25.],
       [39., 23., 16.]])

In [28]:
# max / min / sum / product

np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)

# accessing max / min from each and every row / col 
# using axis = 1 (row - x axis) axis = 0 (col - y axis)
np.max(a1,axis=1)
np.max(a1,axis=0)

# row / col wise prod / sum using axis
np.prod(a1,axis=0)

array([  585., 24656., 37600.])