Boolean Indexing

In [2]:
import numpy as np

In [3]:
a = np.random.randint(1,100,24).reshape(6,4)

In [4]:
# numbers greater than 50

In [5]:
a > 50

array([[False,  True,  True, False],
       [ True,  True, False, False],
       [ True,  True,  True,  True],
       [False,  True, False, False],
       [False, False,  True, False],
       [ True,  True,  True,  True]])

In [6]:
a[a > 50]

array([88, 82, 90, 60, 70, 55, 81, 52, 90, 70, 81, 56, 67, 66])

In [7]:
# finding out even numbers 
a % 2 == 0

array([[ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True, False, False,  True],
       [False,  True,  True, False],
       [ True,  True,  True, False],
       [False,  True, False,  True]])

In [8]:
a[a % 2 == 0]

array([ 2, 88, 82, 90, 60, 38, 18, 70, 52, 90, 10, 46, 10, 70, 56, 66])

In [9]:
# greater than 50 and even
a[(a > 50) & (a % 2 == 0)]  # used bitwise & not the logical and

array([88, 82, 90, 60, 70, 52, 90, 70, 56, 66])

In [12]:
# find all numbers not divisible by 7
a[~(a % 7 == 0)]

array([ 2, 88, 82,  5, 90, 60, 38, 18, 55, 81, 52, 11, 90, 10, 29, 46, 10,
       27, 81, 67, 66])

Broadcasting

In [15]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
a+b

array([[ 6,  8, 10],
       [12, 14, 16]])

In [17]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
a
b

array([[0, 1, 2]])

In [18]:
a + b

array([[0, 2, 4],
       [3, 5, 7]])