Boolean Indexing

In [2]:
import numpy as np

In [3]:
a = np.random.randint(1,100,24).reshape(6,4)

In [4]:
# numbers greater than 50

In [5]:
a > 50

array([[False,  True,  True, False],
       [ True,  True, False, False],
       [ True,  True,  True,  True],
       [False,  True, False, False],
       [False, False,  True, False],
       [ True,  True,  True,  True]])

In [6]:
a[a > 50]

array([88, 82, 90, 60, 70, 55, 81, 52, 90, 70, 81, 56, 67, 66])

In [7]:
# finding out even numbers 
a % 2 == 0

array([[ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True, False, False,  True],
       [False,  True,  True, False],
       [ True,  True,  True, False],
       [False,  True, False,  True]])

In [8]:
a[a % 2 == 0]

array([ 2, 88, 82, 90, 60, 38, 18, 70, 52, 90, 10, 46, 10, 70, 56, 66])

In [9]:
# greater than 50 and even
a[(a > 50) & (a % 2 == 0)]  # used bitwise & not the logical and

array([88, 82, 90, 60, 70, 52, 90, 70, 56, 66])

In [12]:
# find all numbers not divisible by 7
a[~(a % 7 == 0)]

array([ 2, 88, 82,  5, 90, 60, 38, 18, 55, 81, 52, 11, 90, 10, 29, 46, 10,
       27, 81, 67, 66])

Broadcasting

Rules : 
if dimesnions not same we increase the smaller d to big untl it matches the bigger one


if there is no one to strecth even if the dim. are same error occurs


1. Make the two arrays have the same number of dimensions.

If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.


2. Make each dimension of the two arrays the same size.

If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised

In [15]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
a+b

array([[ 6,  8, 10],
       [12, 14, 16]])

In [17]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
a
b

array([[0, 1, 2]])

In [18]:
a + b

array([[0, 2, 4],
       [3, 5, 7]])

In [4]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)
print(a)
print(b)
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [5]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)
print(a)
print(b)
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [7]:
a = np.arange(3,6).reshape(3,1)
b = np.arange(3).reshape(1,3)
print(a)
print(b)
print(a+b)

[[3]
 [4]
 [5]]
[[0 1 2]]
[[3 4 5]
 [4 5 6]
 [5 6 7]]


In [9]:
a = np.arange(3,6).reshape(1,3)
b = np.arange(4).reshape(4,1)
print(a)
print(b)
print(a+b)

[[3 4 5]]
[[0]
 [1]
 [2]
 [3]]
[[3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]]


In [10]:
a = np.array([1])
b = np.arange(4).reshape(2,2)
print(a)
print(b)
print(a+b)

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [11]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)
print(a)
print(b)
print(a+b)

      # even if dimensions are same there is no 1 which we can stretch

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [12]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)
print(a)
print(b)
print(a+b)

# even if dimensions are same there is no 1 which we can stretch

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 